# constants
# solresol text editor v0.1. released 5/1/2020 (dd/mm/yyyy)
# all code by CUBE
# all stenograph images by misolsi misido, owner of the la lasiresa discord server

import pygame

numbers_table = {
    # normal
    "1": "do",
    "2": "re",
    "3": "mi",
    "4": "fa",
    "5": "sol",
    "6": "la",
    "7": "si",

    # accented
    "q": "d1",
    "w": "r1",
    "e": "m1",
    "r": "f1",
    "t": "s1l",
    "y": "l1",
    "u": "s1",

    # plural normal
    "a": "ddo",
    "s": "rre",
    "d": "mmi",
    "f": "ffa",
    "g": "ssol",
    "h": "lla",
    "j": "ssi",

    # plural accented
    "z": "dd1",
    "x": "rr1",
    "c": "mm1",
    "v": "ff1",
    "b": "ss1l",
    "n": "ll1",
    "m": "ss1"
}

plural_table = {
    # normal
    "1": "a",
    "2": "s",
    "3": "d",
    "4": "f",
    "5": "g",
    "6": "h",
    "7": "j",

    # accented
    "q": "z",
    "w": "x",
    "e": "c",
    "r": "v",
    "t": "b",
    "y": "n",
    "u": "m"
}

controlchars = ["S", "R"]

letterchars = ["1", "2", "3", "4", "5", "6", "7",
               "q", "w", "e", "r", "t", "y", "u"]

inputmap = {
    # normal
    "do": "1",
    "re": "2",
    "mi": "3",
    "fa": "4",
    "sol": "5",
    "la": "6",
    "si": "7",

    # accented
    "d1": "q",
    "r1": "w",
    "m1": "e",
    "f1": "r",
    "s1l": "t",
    "l1": "y",
    "s1": "u",

    # controls
    "SPACE": "S",
    "NEWLINE": "R",

    "PLURAL": "P",
    "BACKSPACE": "B",

    "UPSIZE": "U",
    "DOWNSIZE": "D"
}

midiinputmap = {
    # normal
    "do": "C4",
    "re": "D4",
    "mi": "E4",
    "fa": "F4",
    "sol": "G4",
    "la": "A4",
    "si": "B4",

    # accented
    "d1": "C5",
    "r1": "D5",
    "m1": "E5",
    "f1": "F5",
    "s1l": "G5",
    "l1": "A5",
    "s1": "B5",

    # controls
    "SPACE": "S",
    "NEWLINE": "R",

    "PLURAL": "P",
    "BACKSPACE": "B",

    "UPSIZE": "U",
    "DOWNSIZE": "D"
}

allinputs = ["do",
             "re",
             "mi",
             "fa",
             "sol",
             "la",
             "si",

             # accented
             "d1",
             "r1",
             "m1",
             "f1",
             "s1l",
             "l1",
             "s1",

             # controls
             "SPACE",
             "NEWLINE",

             "PLURAL",
             "BACKSPACE",

             "UPSIZE",
             "DOWNSIZE"
             ]

wordlengthlimit = 5

pygame_key_map = {
    "backspace": pygame.K_BACKSPACE,
    "tab": pygame.K_TAB,
    "clear": pygame.K_CLEAR,
    "return": pygame.K_RETURN,
    "pause": pygame.K_PAUSE,
    "escape": pygame.K_ESCAPE,
    "space": pygame.K_SPACE,
    "exclaim": pygame.K_EXCLAIM,
    "quotedbl": pygame.K_QUOTEDBL,
    "hash": pygame.K_HASH,
    "dollar": pygame.K_DOLLAR,
    "ampersand": pygame.K_AMPERSAND,
    "quote": pygame.K_QUOTE,
    "left parenthesis": pygame.K_LEFTPAREN,
    "right parenthesis": pygame.K_RIGHTPAREN,
    "asterisk": pygame.K_ASTERISK,
    "plus sign": pygame.K_PLUS,
    "comma": pygame.K_COMMA,
    "minus sign": pygame.K_MINUS,
    "period": pygame.K_PERIOD,
    "forward slash": pygame.K_SLASH,
    "0": pygame.K_0,
    "1": pygame.K_1,
    "2": pygame.K_2,
    "3": pygame.K_3,
    "4": pygame.K_4,
    "5": pygame.K_5,
    "6": pygame.K_6,
    "7": pygame.K_7,
    "8": pygame.K_8,
    "9": pygame.K_9,
    "colon": pygame.K_COLON,
    "semicolon": pygame.K_SEMICOLON,
    "less-than sign": pygame.K_LESS,
    "equals sign": pygame.K_EQUALS,
    "greater-than sign": pygame.K_GREATER,
    "question mark": pygame.K_QUESTION,
    "at": pygame.K_AT,
    "left bracket": pygame.K_LEFTBRACKET,
    "backslash": pygame.K_BACKSLASH,
    "right bracket": pygame.K_RIGHTBRACKET,
    "caret": pygame.K_CARET,
    "underscore": pygame.K_UNDERSCORE,
    "grave": pygame.K_BACKQUOTE,
    "a": pygame.K_a,
    "b": pygame.K_b,
    "c": pygame.K_c,
    "d": pygame.K_d,
    "e": pygame.K_e,
    "f": pygame.K_f,
    "g": pygame.K_g,
    "h": pygame.K_h,
    "i": pygame.K_i,
    "j": pygame.K_j,
    "k": pygame.K_k,
    "l": pygame.K_l,
    "m": pygame.K_m,
    "n": pygame.K_n,
    "o": pygame.K_o,
    "p": pygame.K_p,
    "q": pygame.K_q,
    "r": pygame.K_r,
    "s": pygame.K_s,
    "t": pygame.K_t,
    "u": pygame.K_u,
    "v": pygame.K_v,
    "w": pygame.K_w,
    "x": pygame.K_x,
    "y": pygame.K_y,
    "z": pygame.K_z,
    "delete": pygame.K_DELETE,
    "keypad 0": pygame.K_KP0,
    "keypad 1": pygame.K_KP1,
    "keypad 2": pygame.K_KP2,
    "keypad 3": pygame.K_KP3,
    "keypad 4": pygame.K_KP4,
    "keypad 5": pygame.K_KP5,
    "keypad 6": pygame.K_KP6,
    "keypad 7": pygame.K_KP7,
    "keypad 8": pygame.K_KP8,
    "keypad 9": pygame.K_KP9,
    "keypad period": pygame.K_KP_PERIOD,
    "keypad divide": pygame.K_KP_DIVIDE,
    "keypad multiply": pygame.K_KP_MULTIPLY,
    "keypad minus": pygame.K_KP_MINUS,
    "keypad plus": pygame.K_KP_PLUS,
    "keypad enter": pygame.K_KP_ENTER,
    "keypad equals": pygame.K_KP_EQUALS,
    "up arrow": pygame.K_UP,
    "down arrow": pygame.K_DOWN,
    "right arrow": pygame.K_RIGHT,
    "left arrow": pygame.K_LEFT,
    "insert": pygame.K_INSERT,
    "home": pygame.K_HOME,
    "end": pygame.K_END,
    "page up": pygame.K_PAGEUP,
    "page down": pygame.K_PAGEDOWN,
    "F1": pygame.K_F1,
    "F2": pygame.K_F2,
    "F3": pygame.K_F3,
    "F4": pygame.K_F4,
    "F5": pygame.K_F5,
    "F6": pygame.K_F6,
    "F7": pygame.K_F7,
    "F8": pygame.K_F8,
    "F9": pygame.K_F9,
    "F10": pygame.K_F10,
    "F11": pygame.K_F11,
    "F12": pygame.K_F12,
    "F13": pygame.K_F13,
    "F14": pygame.K_F14,
    "F15": pygame.K_F15,
    "numlock": pygame.K_NUMLOCK,
    "capslock": pygame.K_CAPSLOCK,
    "scrollock": pygame.K_SCROLLOCK,
    "right shift": pygame.K_RSHIFT,
    "left shift": pygame.K_LSHIFT,
    "right control": pygame.K_RCTRL,
    "left control": pygame.K_LCTRL,
    "right alt": pygame.K_RALT,
    "left alt": pygame.K_LALT,
    "right meta": pygame.K_RMETA,
    "left meta": pygame.K_LMETA,
    "left Windows key": pygame.K_LSUPER,
    "right Windows key": pygame.K_RSUPER,
    "mode shift": pygame.K_MODE,
    "help": pygame.K_HELP,
    "print screen": pygame.K_PRINT,
    "sysrq": pygame.K_SYSREQ,
    "break": pygame.K_BREAK,
    "menu": pygame.K_MENU,
    "power": pygame.K_POWER,
    "Euro": pygame.K_EURO
}

midi_key_map = {
 	"C-1": 0,
	"C#-1": 1,
	"D-1": 2,
	"D#-1": 3,
	"E-1": 4,
	"F-1": 5,
	"F#-1": 6,
	"G-1": 7,
	"G#-1": 8,
	"A-1": 9,
	"A#-1": 10,
	"B-1": 11,
	"C0": 12,
	"C#0": 13,
	"D0": 14,
	"D#0": 15,
	"E0": 16,
	"F0": 17,
	"F#0": 18,
	"G0": 19,
	"G#0": 20,
	"A0": 21,
	"A#0": 22,
	"B0": 23,
	"C1": 24,
	"C#1": 25,
	"D1": 26,
	"D#1": 27,
	"E1": 28,
	"F1": 29,
	"F#1": 30,
	"G1": 31,
	"G#1": 32,
	"A1": 33,
	"A#1": 34,
	"B1": 35,
	"C2": 36,
	"C#2": 37,
	"D2": 38,
	"D#2": 39,
	"E2": 40,
	"F2": 41,
	"F#2": 42,
	"G2": 43,
	"G#2": 44,
	"A2": 45,
	"A#2": 46,
	"B2": 47,
	"C3": 48,
	"C#3": 49,
	"D3": 50,
	"D#3": 51,
	"E3": 52,
	"F3": 53,
	"F#3": 54,
	"G3": 55,
	"G#3": 56,
	"A3": 57,
	"A#3": 58,
	"B3": 59,
	"C4": 60,
	"C#4": 61,
	"D4": 62,
	"D#4": 63,
	"E4": 64,
	"F4": 65,
	"F#4": 66,
	"G4": 67,
	"G#4": 68,
	"A4": 69,
	"A#4": 70,
	"B4": 71,
	"C5": 72,
	"C#5": 73,
	"D5": 74,
	"D#5": 75,
	"E5": 76,
	"F5": 77,
	"F#5": 78,
	"G5": 79,
	"G#5": 80,
	"A5": 81,
	"A#5": 82,
	"B5": 83,
	"C6": 84,
	"C#6": 85,
	"D6": 86,
	"D#6": 87,
	"E6": 88,
	"F6": 89,
	"F#6": 90,
	"G6": 91,
	"G#6": 92,
	"A6": 93,
	"A#6": 94,
	"B6": 95,
	"C7": 96,
	"C#7": 97,
	"D7": 98,
	"D#7": 99,
	"E7": 100,
	"F7": 101,
	"F#7": 102,
	"G7": 103,
	"G#7": 104,
	"A7": 105,
	"A#7": 106,
	"B7": 107,
	"C8": 108,
	"C#8": 109,
	"D8": 110,
	"D#8": 111,
	"E8": 112,
	"F8": 113,
	"F#8": 114,
	"G8": 115,
	"G#8": 116,
	"A8": 117,
	"A#8": 118,
	"B8": 119,
	"C9": 120,
	"C#9": 121,
	"D9": 122,
	"D#9": 123,
	"E9": 124,
	"F9": 125,
	"F#9": 126,
	"G9": 127,

    # for using control functions in the future
    "placeholder1": 1001,
    "placeholder2": 1002,
    "placeholder3": 1003,
    "placeholder4": 1004,
    "placeholder5": 1005,
    "placeholder6": 1006
}
